http  {
	include /etc/nginx/mime.types;

	server {
		listen 443 ssl;
		listen [::]:80;

		ssl_certificate /etc/nginx/ssl/localhost.crt;
		ssl_certificate_key /etc/nginx/ssl/localhost.key;
		ssl_protocols TLSv1.3;

		root /var/www/html;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php$args;
		}
	}
}

events {}
